module.exports = {
  schemaVersion: '1.0.0',
  reportDir: 'proving-ground/reports/cli-sections',
  commandDescriptorPath: 'sdk/generated/command-descriptors.json',
  model: {
    provider: 'minimax',
    apiKeyEnv: 'MINIMAX_API_KEY',
    model: 'MiniMax-M2.7-highspeed',
    baseUrl: 'https://api.minimax.io/v1',
    temperature: 0.2,
    reasoningSplit: true,
    timeoutMs: 120000,
    maxAttempts: 3,
    retryDelayMs: 3000,
  },
  researchLoop: {
    goal: 'Make the Pandora CLI clearer, faster, and simpler without changing what each command means.',
    mode: 'workspace',
    iterationsPerSection: 50,
    allowDirtyTree: false,
    maxSlowdownRatio: 1.02,
    finalValidation: [
      'npm run verify:tests',
    ],
  },
  baton: {
    reportDir: 'proving-ground/reports/baton',
    laneCount: 10,
    maxParallelWorkers: 10,
    heartbeatTimeoutMs: 30000,
    cleanupPolicy: 'manual',
    pausePollMs: 250,
  },
  worker: {
    timeBudgetMs: 1800000,
    tokenBudget: 120000,
    oneAttempt: true,
    maxModelCalls: 1,
    promptVersion: 'baton-v1',
  },
  council: {
    roles: [
      'correctness',
      'determinism',
      'safety',
      'performance',
      'simplicity',
      'goal-fit',
    ],
    quorum: 4,
    reviseCap: 1,
    dedupe: true,
  },
  integration: {
    branchPrefix: 'codex/baton',
    mergeOrder: 'lane-index',
    promotionBranch: 'main',
    worktreeName: 'integration',
  },
  validation: {
    syntheticModel: false,
    syntheticCouncil: false,
    runRealWorktrees: true,
    failureInjection: {},
  },
  sections: [
    {
      id: 'onboarding-contracts',
      title: 'Onboarding And Contracts',
      description: 'Clarify startup, doctoring, schema, and capability discovery so new operators and agents get to the point faster.',
      commandPrefixes: [
        'bootstrap',
        'capabilities',
        'doctor',
        'explain',
        'export',
        'help',
        'init-env',
        'schema',
        'setup',
        'suggest',
        'version',
      ],
      focusFiles: [
        'cli/lib/bootstrap_command_service.cjs',
        'cli/lib/setup_command_service.cjs',
        'cli/lib/doctor_service.cjs',
        'cli/lib/schema_command_service.cjs',
        'cli/lib/capabilities_command_service.cjs',
        'cli/lib/explain_command_service.cjs',
      ],
      helpCommands: [
        'node cli/pandora.cjs setup --help',
        'node cli/pandora.cjs doctor --help',
        'node cli/pandora.cjs capabilities --help',
        'node cli/pandora.cjs schema --help',
      ],
      quickValidation: [
        'node --test tests/unit/bootstrap_command_service.test.cjs tests/unit/sdk_contract_service.test.cjs tests/unit/explain_command_service.test.cjs',
      ],
      fullValidation: [
        'node --test tests/cli/explain.integration.test.cjs tests/cli/mcp.integration.test.cjs',
      ],
      allowNeutralKeep: true,
    },
    {
      id: 'policy-profile-recipe',
      title: 'Policy, Profiles, And Recipes',
      description: 'Make execution guidance, profile choice, and reusable recipes easier to understand without changing the safety rules.',
      commandPrefixes: [
        'fund-check',
        'policy',
        'profile',
        'recipe',
      ],
      focusFiles: [
        'cli/lib/policy_command_service.cjs',
        'cli/lib/profile_command_service.cjs',
        'cli/lib/policy_profile_guidance_service.cjs',
        'cli/lib/recipe_command_service.cjs',
        'cli/lib/recipe_runtime_service.cjs',
      ],
      helpCommands: [
        'node cli/pandora.cjs policy --help',
        'node cli/pandora.cjs profile --help',
        'node cli/pandora.cjs recipe --help',
      ],
      quickValidation: [
        'node --test tests/unit/policy_profile_services.test.cjs tests/unit/policy_profile_contracts.test.cjs tests/unit/recipe_runtime.test.cjs',
      ],
      fullValidation: [
        'node --test tests/cli/policy_profile_cli.integration.test.cjs tests/cli/policy_profile_mcp.integration.test.cjs tests/cli/recipe.integration.test.cjs',
      ],
      allowNeutralKeep: true,
    },
    {
      id: 'markets-liquidity-lifecycle',
      title: 'Markets, Liquidity, And Lifecycle',
      description: 'Keep market creation, trading, liquidity, and closeout flows lean while preserving the exact execution behavior.',
      commandPrefixes: [
        'claim',
        'clone-bet',
        'launch',
        'lifecycle',
        'lp',
        'markets',
        'polls',
        'positions',
        'quote',
        'resolve',
        'sell',
      ],
      focusFiles: [
        'cli/lib/markets_create_command_service.cjs',
        'cli/lib/trade_command_service.cjs',
        'cli/lib/lp_command_service.cjs',
        'cli/lib/market_admin_service.cjs',
        'cli/lib/lifecycle_command_service.cjs',
      ],
      helpCommands: [
        'node cli/pandora.cjs markets --help',
        'node cli/pandora.cjs launch --help',
        'node cli/pandora.cjs lp --help',
        'node cli/pandora.cjs resolve --help',
      ],
      quickValidation: [
        'node --test tests/unit/markets_hype_command_service.test.cjs tests/unit/lp_command_service.test.cjs tests/unit/claim_command_service.test.cjs tests/unit/market_admin_resolution_state.test.cjs',
      ],
      fullValidation: [
        'node --test tests/cli/cli.integration.market_ops.cjs',
      ],
    },
    {
      id: 'mirror-deploy-lifecycle',
      title: 'Mirror Deploy And Lifecycle',
      description: 'Keep deploy, verify, resume, replay, and general mirror control readable and safe.',
      commandPrefixes: [
        'mirror',
      ],
      focusFiles: [
        'cli/lib/mirror_command_service.cjs',
        'cli/lib/mirror_service.cjs',
        'cli/lib/mirror_manifest_store.cjs',
        'cli/lib/mirror_deploy_guard_store.cjs',
        'cli/lib/mirror_surface_service.cjs',
      ],
      helpCommands: [
        'node cli/pandora.cjs mirror --help',
        'node cli/pandora.cjs mirror deploy --help',
        'node cli/pandora.cjs mirror go --help',
        'node cli/pandora.cjs mirror verify --help',
      ],
      quickValidation: [
        'node --test tests/unit/mirror_service_rules.test.cjs tests/unit/mirror_manifest_store.test.cjs tests/unit/mirror_go_regressions.test.cjs tests/unit/mirror_surface_service.test.cjs',
      ],
      fullValidation: [
        'node --test tests/cli/cli.integration.mirror.cjs tests/cli/mirror_logs.integration.test.cjs tests/cli/mirror_replay.integration.test.cjs',
      ],
      allowNeutralKeep: true,
    },
    {
      id: 'pandora-mirroring-mode',
      title: 'Pandora Mirroring Mode',
      description: 'Make Pandora-only price mirroring easier to follow and lighter to execute.',
      commandPrefixes: [
        'mirror.sync',
      ],
      focusFiles: [
        'cli/lib/mirror_sync_service.cjs',
        'cli/lib/mirror_sizing_service.cjs',
        'cli/lib/mirror_surface_service.cjs',
        'cli/lib/mirror_state_store.cjs',
      ],
      helpCommands: [
        'node cli/pandora.cjs mirror sync --help',
      ],
      quickValidation: [
        'node --test tests/unit/mirror_sync_execution.test.cjs tests/unit/mirror_sync_skip_initial_hedge.test.cjs tests/unit/mirror_simulate_mc.test.cjs',
      ],
      fullValidation: [
        'node --test tests/cli/cli.integration.mirror.cjs',
      ],
    },
    {
      id: 'polymarket-hedge-mode',
      title: 'Polymarket Hedge Mode',
      description: 'Keep hedge-only execution, daemon state, and inventory logic explicit and resilient.',
      commandPrefixes: [
        'mirror.hedge',
      ],
      focusFiles: [
        'cli/lib/mirror_hedge_service.cjs',
        'cli/lib/mirror_hedge_daemon_service.cjs',
        'cli/lib/mirror_hedge_state_store.cjs',
        'cli/lib/polymarket_trade_adapter.cjs',
      ],
      helpCommands: [
        'node cli/pandora.cjs mirror hedge --help',
        'node cli/pandora.cjs mirror hedge status --help',
      ],
      quickValidation: [
        'node --test tests/unit/mirror_hedge_service.test.cjs tests/unit/mirror_hedge_daemon_service.test.cjs tests/unit/mirror_hedge_flags.test.cjs',
      ],
      fullValidation: [
        'node --test tests/cli/mirror_hedge_daemon_sandbox.integration.test.cjs tests/cli/mirror_health_panic.integration.test.cjs',
      ],
    },
    {
      id: 'polymarket-ops-funding',
      title: 'Polymarket Ops And Funding',
      description: 'Simplify direct Polymarket checks, approvals, balances, and funding without hiding risk.',
      commandPrefixes: [
        'fees',
        'polymarket',
        'portfolio',
      ],
      focusFiles: [
        'cli/lib/polymarket_command_service.cjs',
        'cli/lib/polymarket_ops_service.cjs',
        'cli/lib/polymarket_adapter.cjs',
        'cli/lib/fees_command_service.cjs',
        'cli/lib/dashboard_fund_service.cjs',
      ],
      helpCommands: [
        'node cli/pandora.cjs polymarket --help',
        'node cli/pandora.cjs fees --help',
        'node cli/pandora.cjs dashboard --help',
      ],
      quickValidation: [
        'node --test tests/unit/polymarket_adapter.test.cjs tests/unit/polymarket_ops_service.test.cjs tests/unit/polymarket_trade_adapter.test.cjs tests/unit/fees_command_service.test.cjs',
      ],
      fullValidation: [
        'node --test tests/cli/cli.integration.operator.cjs tests/cli/dashboard_fund.integration.test.cjs',
      ],
    },
    {
      id: 'operations-risk-watch',
      title: 'Operations, Risk, And Watch',
      description: 'Keep long-running operations, receipts, watch flows, and panic stops simple under pressure.',
      commandPrefixes: [
        'autopilot',
        'dashboard',
        'operations',
        'risk',
        'watch',
        'webhook',
      ],
      focusFiles: [
        'cli/lib/operations_command_service.cjs',
        'cli/lib/operation_service.cjs',
        'cli/lib/risk_command_service.cjs',
        'cli/lib/watch_command_service.cjs',
        'cli/lib/webhook_service.cjs',
      ],
      helpCommands: [
        'node cli/pandora.cjs operations --help',
        'node cli/pandora.cjs watch --help',
        'node cli/pandora.cjs risk --help',
      ],
      quickValidation: [
        'node --test tests/unit/operations_command_service.test.cjs tests/unit/operation_service.test.cjs tests/unit/watch_risk_command_service.test.cjs tests/unit/watch_risk_policy_service.test.cjs tests/unit/risk_guard_service.test.cjs tests/unit/webhook_service.test.cjs',
      ],
      fullValidation: [
        'node --test tests/cli/watch_risk.integration.test.cjs tests/cli/dashboard_fund.integration.test.cjs',
      ],
    },
    {
      id: 'sports-model-stream',
      title: 'Sports, Models, And Streams',
      description: 'Trim the sports and model surfaces so live data, scoring, and creation logic stay understandable.',
      commandPrefixes: [
        'analyze',
        'events',
        'history',
        'leaderboard',
        'model',
        'odds',
        'sports',
        'stream',
      ],
      focusFiles: [
        'cli/lib/sports_command_service.cjs',
        'cli/lib/sports_creation_service.cjs',
        'cli/lib/sports_sync_service.cjs',
        'cli/lib/model_command_service.cjs',
        'cli/lib/stream_command_service.cjs',
      ],
      helpCommands: [
        'node cli/pandora.cjs sports --help',
        'node cli/pandora.cjs model --help',
        'node cli/pandora.cjs stream --help',
      ],
      quickValidation: [
        'node --test tests/unit/sports_creation.test.cjs tests/unit/sports_resolve_plan.test.cjs tests/unit/sports_sync.test.cjs tests/unit/sports_timing.test.cjs tests/unit/model_calibrate.test.cjs tests/unit/model_correlation.test.cjs tests/unit/model_diagnose.test.cjs tests/unit/odds_history_service.test.cjs tests/unit/brier_scoring.test.cjs',
      ],
      fullValidation: [
        'node --test tests/cli/sports.integration.test.cjs tests/cli/stream.integration.test.cjs',
      ],
    },
    {
      id: 'agent-mcp-bridge-arb',
      title: 'Agent, MCP, Bridge, Arb, And Simulation',
      description: 'Keep advanced agent surfaces and cross-venue tooling compact enough that operators and agents can still reason about them.',
      commandPrefixes: [
        'agent',
        'arb',
        'bridge',
        'debug',
        'mcp',
        'scan',
        'simulate',
        'trade',
      ],
      focusFiles: [
        'cli/lib/agent_command_service.cjs',
        'cli/lib/mcp_server_service.cjs',
        'cli/lib/bridge_command_service.cjs',
        'cli/lib/arb_command_service.cjs',
        'cli/lib/simulate_command_service.cjs',
      ],
      helpCommands: [
        'node cli/pandora.cjs agent --help',
        'node cli/pandora.cjs mcp --help',
        'node cli/pandora.cjs bridge --help',
        'node cli/pandora.cjs arb --help',
        'node cli/pandora.cjs simulate --help',
      ],
      quickValidation: [
        'node --test tests/unit/agent_acceptance_runner.test.cjs tests/unit/agent_contract_registry.test.cjs tests/unit/mcp_tool_registry_agent.test.cjs tests/unit/bridge_command_service.test.cjs tests/unit/combinatorial_arb.test.cjs tests/unit/simulate_command_service.test.cjs',
      ],
      fullValidation: [
        'node --test tests/cli/agent_workflow.integration.test.cjs tests/cli/bridge.integration.test.cjs tests/cli/cli.integration.arbitrage.cjs',
      ],
    },
  ],
};
