'use strict';

const BUILTIN_RECIPES = Object.freeze([
  Object.freeze({
    schemaVersion: '1.0.0',
    kind: 'recipe',
    id: 'mirror.sync.paper-safe',
    version: '1.0.0',
    displayName: 'Mirror Sync (Paper Safe)',
    description: 'Start a mirror sync daemon in paper mode with conservative, no-write defaults.',
    tool: 'mirror.sync.start',
    commandTemplate: ['mirror', 'sync', 'start', '--paper', '--market-address', '{{market-address}}'],
    inputs: [
      { key: 'market-address', type: 'string', description: 'Pandora market address to sync.', required: true },
    ],
    defaultPolicy: 'paper-trading',
    defaultProfile: null,
    execution: {
      safeByDefault: true,
      operationExpected: true,
      mutating: false,
      supportsRemote: true,
    },
    tags: ['mirror', 'sync', 'paper'],
    docs: 'docs/skills/mirror-operations.md',
    benchmark: 'recipe-mirror-sync-paper',
    firstParty: true,
  }),
  Object.freeze({
    schemaVersion: '1.0.0',
    kind: 'recipe',
    id: 'claim.all.finalized',
    version: '1.0.0',
    displayName: 'Claim All Finalized Markets',
    description: 'Run a safe dry-run claim sweep across all finalized positions.',
    tool: 'claim',
    commandTemplate: ['claim', '--all', '--dry-run'],
    inputs: [],
    defaultPolicy: 'paper-trading',
    defaultProfile: null,
    execution: {
      safeByDefault: true,
      operationExpected: true,
      mutating: false,
      supportsRemote: true,
    },
    tags: ['claim', 'closeout', 'wallet'],
    docs: 'docs/skills/portfolio-closeout.md',
    benchmark: 'recipe-claim-all-finalized',
    firstParty: true,
  }),
  Object.freeze({
    schemaVersion: '1.0.0',
    kind: 'recipe',
    id: 'mirror.close.all',
    version: '1.0.0',
    displayName: 'Mirror Closeout Plan',
    description: 'Generate a safe mirror close plan across all tracked mirrors without submitting live writes.',
    tool: 'mirror.close',
    commandTemplate: ['mirror', 'close', '--all', '--dry-run'],
    inputs: [],
    defaultPolicy: 'paper-trading',
    defaultProfile: null,
    execution: {
      safeByDefault: true,
      operationExpected: true,
      mutating: false,
      supportsRemote: true,
    },
    tags: ['mirror', 'closeout', 'operations'],
    docs: 'docs/skills/portfolio-closeout.md',
    benchmark: 'recipe-mirror-close-all',
    firstParty: true,
  }),
  Object.freeze({
    schemaVersion: '1.0.0',
    kind: 'recipe',
    id: 'sports.sync.paper-safe',
    version: '1.0.0',
    displayName: 'Sports Sync (Paper Safe)',
    description: 'Start a sports sync daemon in paper mode for one event id.',
    tool: 'sports.sync.start',
    commandTemplate: ['sports', 'sync', 'start', '--paper', '--event-id', '{{event-id}}'],
    inputs: [
      { key: 'event-id', type: 'string', description: 'Normalized sports event id.', required: true },
    ],
    defaultPolicy: 'paper-trading',
    defaultProfile: null,
    execution: {
      safeByDefault: true,
      operationExpected: true,
      mutating: false,
      supportsRemote: true,
    },
    tags: ['sports', 'sync', 'paper'],
    docs: 'docs/skills/trading-workflows.md',
    benchmark: 'recipe-sports-sync-paper',
    firstParty: true,
  }),
]);

module.exports = {
  BUILTIN_RECIPES,
};
