'use strict';

const BUILTIN_RECIPES = Object.freeze([
  Object.freeze({
    schemaVersion: '1.0.0',
    kind: 'recipe',
    id: 'mirror.sync.paper-safe',
    version: '1.0.0',
    displayName: 'Mirror Sync (Paper Safe)',
    description: 'Start a mirror sync daemon in paper mode with conservative, no-write defaults.',
    summary: 'Paper-mode mirror sync starter for one Pandora market.',
    tool: 'mirror.sync.start',
    commandTemplate: ['mirror', 'sync', 'start', '--paper', '--market-address', '{{market-address}}'],
    inputs: [
      { key: 'market-address', type: 'string', description: 'Pandora market address to sync.', required: true },
    ],
    defaultPolicy: 'paper-trading',
    defaultProfile: null,
    execution: {
      safeByDefault: true,
      operationExpected: true,
      mutating: false,
      supportsRemote: false,
    },
    tags: ['mirror', 'sync', 'paper'],
    source: 'first-party',
    approvalStatus: 'approved',
    riskLevel: 'paper',
    docs: 'docs/skills/mirror-operations.md',
    benchmark: 'recipe-mirror-sync-paper',
  }),
  Object.freeze({
    schemaVersion: '1.0.0',
    kind: 'recipe',
    id: 'claim.all.finalized',
    version: '1.0.0',
    displayName: 'Claim All Finalized Markets',
    description: 'Run a safe dry-run claim sweep across all finalized positions.',
    summary: 'Dry-run claim sweep for finalized wallet positions.',
    tool: 'claim',
    commandTemplate: ['claim', '--all', '--dry-run'],
    inputs: [],
    defaultPolicy: 'paper-trading',
    defaultProfile: null,
    execution: {
      safeByDefault: true,
      operationExpected: true,
      mutating: false,
      supportsRemote: false,
    },
    tags: ['claim', 'closeout', 'wallet'],
    source: 'first-party',
    approvalStatus: 'approved',
    riskLevel: 'dry-run',
    docs: 'docs/skills/portfolio-closeout.md',
    benchmark: 'recipe-claim-all-finalized',
  }),
  Object.freeze({
    schemaVersion: '1.0.0',
    kind: 'recipe',
    id: 'mirror.close.all',
    version: '1.0.0',
    displayName: 'Mirror Closeout Plan',
    description: 'Generate a safe mirror close plan across all tracked mirrors without submitting live writes.',
    summary: 'Dry-run closeout planner for all tracked mirrors.',
    tool: 'mirror.close',
    commandTemplate: ['mirror', 'close', '--all', '--dry-run'],
    inputs: [],
    defaultPolicy: 'paper-trading',
    defaultProfile: null,
    execution: {
      safeByDefault: true,
      operationExpected: true,
      mutating: false,
      supportsRemote: true,
    },
    tags: ['mirror', 'closeout', 'operations'],
    source: 'first-party',
    approvalStatus: 'approved',
    riskLevel: 'dry-run',
    docs: 'docs/skills/portfolio-closeout.md',
    benchmark: 'recipe-mirror-close-all',
  }),
  Object.freeze({
    schemaVersion: '1.0.0',
    kind: 'recipe',
    id: 'sports.sync.paper-safe',
    version: '1.0.0',
    displayName: 'Sports Sync (Paper Safe)',
    description: 'Start a sports sync daemon in paper mode for one event id.',
    summary: 'Paper-mode sports sync starter for one normalized event id.',
    tool: 'sports.sync.start',
    commandTemplate: ['sports', 'sync', 'start', '--paper', '--event-id', '{{event-id}}'],
    inputs: [
      { key: 'event-id', type: 'string', description: 'Normalized sports event id.', required: true },
    ],
    defaultPolicy: 'paper-trading',
    defaultProfile: null,
    execution: {
      safeByDefault: true,
      operationExpected: true,
      mutating: false,
      supportsRemote: true,
    },
    tags: ['sports', 'sync', 'paper'],
    source: 'first-party',
    approvalStatus: 'approved',
    riskLevel: 'paper',
    docs: 'docs/skills/trading-workflows.md',
    benchmark: 'recipe-sports-sync-paper',
  }),
  Object.freeze({
    schemaVersion: '1.0.0',
    kind: 'recipe',
    id: 'resolve.poll.dryrun',
    version: '1.0.0',
    displayName: 'Resolve Poll (Dry Run)',
    description: 'Preview poll resolution without submitting on-chain.',
    summary: 'Dry-run poll resolution preview with operator reason and answer.',
    tool: 'resolve',
    commandTemplate: ['resolve', '--poll-address', '{{poll-address}}', '--answer', '{{answer}}', '--reason', '{{reason}}', '--dry-run'],
    inputs: [
      { key: 'poll-address', type: 'string', description: 'Poll contract address.', required: true },
      { key: 'answer', type: 'string', description: 'Resolution answer (yes|no|invalid).', required: true },
      { key: 'reason', type: 'string', description: 'Operator reason for resolution.', required: true },
    ],
    defaultPolicy: 'paper-trading',
    defaultProfile: null,
    execution: {
      safeByDefault: true,
      operationExpected: false,
      mutating: false,
      supportsRemote: false,
    },
    tags: ['resolve', 'poll', 'dry-run', 'preview'],
    source: 'first-party',
    approvalStatus: 'approved',
    riskLevel: 'dry-run',
    docs: 'docs/skills/portfolio-closeout.md',
    benchmark: null,
  }),
  Object.freeze({
    schemaVersion: '1.0.0',
    kind: 'recipe',
    id: 'resolve.poll.execute',
    version: '1.0.0',
    displayName: 'Resolve Poll (Live)',
    description: 'Execute live poll resolution on-chain.',
    summary: 'Live poll resolution recipe for one poll address.',
    tool: 'resolve',
    commandTemplate: ['resolve', '--poll-address', '{{poll-address}}', '--answer', '{{answer}}', '--reason', '{{reason}}', '--execute'],
    inputs: [
      { key: 'poll-address', type: 'string', description: 'Poll contract address.', required: true },
      { key: 'answer', type: 'string', description: 'Resolution answer (yes|no|invalid).', required: true },
      { key: 'reason', type: 'string', description: 'Operator reason for resolution.', required: true },
    ],
    defaultPolicy: null,
    defaultProfile: null,
    execution: {
      safeByDefault: false,
      operationExpected: true,
      mutating: true,
      supportsRemote: false,
    },
    tags: ['resolve', 'poll', 'live'],
    source: 'first-party',
    approvalStatus: 'approved',
    riskLevel: 'live',
    docs: 'docs/skills/portfolio-closeout.md',
    benchmark: null,
  }),
  Object.freeze({
    schemaVersion: '1.0.0',
    kind: 'recipe',
    id: 'portfolio.snapshot',
    version: '1.0.0',
    displayName: 'Portfolio Snapshot',
    description: 'Get full portfolio overview including LP positions for a wallet.',
    summary: 'Read-only wallet portfolio snapshot with LP exposure.',
    tool: 'portfolio',
    commandTemplate: ['portfolio', '--wallet', '{{wallet}}', '--with-lp'],
    inputs: [
      { key: 'wallet', type: 'string', description: 'Wallet address to inspect.', required: true },
    ],
    defaultPolicy: null,
    defaultProfile: null,
    execution: {
      safeByDefault: true,
      operationExpected: false,
      mutating: false,
      supportsRemote: true,
    },
    tags: ['portfolio', 'snapshot', 'wallet', 'lp'],
    source: 'first-party',
    approvalStatus: 'approved',
    riskLevel: 'read-only',
    docs: 'docs/skills/portfolio-closeout.md',
    benchmark: null,
  }),
  Object.freeze({
    schemaVersion: '1.0.0',
    kind: 'recipe',
    id: 'debug.market.inspect',
    version: '1.0.0',
    displayName: 'Debug Market Inspect',
    description: 'Run full diagnostics on a deployed market including poll, liquidity, and position context.',
    summary: 'Read-only deep market diagnostics for one Pandora market.',
    tool: 'debug.market',
    commandTemplate: ['debug', 'market', '--market-address', '{{market-address}}'],
    inputs: [
      { key: 'market-address', type: 'string', description: 'Pandora market address to inspect.', required: true },
    ],
    defaultPolicy: null,
    defaultProfile: null,
    execution: {
      safeByDefault: true,
      operationExpected: false,
      mutating: false,
      supportsRemote: true,
    },
    tags: ['debug', 'market', 'diagnostics'],
    source: 'first-party',
    approvalStatus: 'approved',
    riskLevel: 'read-only',
    docs: 'docs/skills/command-reference.md',
    benchmark: null,
  }),
  Object.freeze({
    schemaVersion: '1.0.0',
    kind: 'recipe',
    id: 'mirror.plan.poly',
    version: '1.0.0',
    displayName: 'Mirror Plan (Polymarket)',
    description: 'Generate mirror sizing plan from a Polymarket source market with rules and similarity checks.',
    summary: 'Mirror planning recipe for one Polymarket source market.',
    tool: 'mirror.plan',
    commandTemplate: ['mirror', 'plan', '--source', 'polymarket', '--polymarket-slug', '{{polymarket-slug}}', '--with-rules', '--include-similarity'],
    inputs: [
      { key: 'polymarket-slug', type: 'string', description: 'Polymarket market slug.', required: true },
    ],
    defaultPolicy: null,
    defaultProfile: null,
    execution: {
      safeByDefault: true,
      operationExpected: false,
      mutating: false,
      supportsRemote: true,
    },
    tags: ['mirror', 'plan', 'polymarket', 'scouting'],
    source: 'first-party',
    approvalStatus: 'approved',
    riskLevel: 'read-only',
    docs: 'docs/skills/mirror-operations.md',
    benchmark: null,
  }),
  Object.freeze({
    schemaVersion: '1.0.0',
    kind: 'recipe',
    id: 'pari.deploy.preview',
    version: '1.0.0',
    displayName: 'Pari-Mutuel Deploy Preview',
    description: 'Dry-run a pari-mutuel market deployment to preview parameters, distribution, and cost without spending gas.',
    summary: 'Dry-run canonical parimutuel market creation payload.',
    tool: 'markets.create.run',
    commandTemplate: [
      'markets', 'create', 'run',
      '--market-type', 'parimutuel',
      '--category', '{{category}}',
      '--question', '{{question}}',
      '--rules', '{{rules}}',
      '--sources', '{{source1}}', '{{source2}}',
      '--target-timestamp', '{{target-timestamp}}',
      '--liquidity-usdc', '{{liquidity-usdc}}',
      '--yes-reserve-weight-pct', '{{yes-reserve-weight-pct}}',
      '--no-reserve-weight-pct', '{{no-reserve-weight-pct}}',
      '--curve-flattener', '{{curve-flattener}}',
      '--curve-offset', '{{curve-offset}}',
      '--dry-run',
    ],
    inputs: [
      { key: 'category', type: 'string', description: 'Market category.', required: true },
      { key: 'question', type: 'string', description: 'Market question.', required: true },
      { key: 'rules', type: 'string', description: 'Resolution rules.', required: true },
      { key: 'source1', type: 'string', description: 'First source URL.', required: true },
      { key: 'source2', type: 'string', description: 'Second source URL.', required: true },
      { key: 'target-timestamp', type: 'string', description: 'ISO-8601 or unix target timestamp.', required: true },
      { key: 'liquidity-usdc', type: 'number', description: 'Initial liquidity in USDC.', required: true },
      { key: 'yes-reserve-weight-pct', type: 'number', description: 'YES reserve weight percent.', required: true },
      { key: 'no-reserve-weight-pct', type: 'number', description: 'NO reserve weight percent.', required: true },
      { key: 'curve-flattener', type: 'number', description: 'Pari-mutuel curve flattener.', required: true },
      { key: 'curve-offset', type: 'number', description: 'Pari-mutuel curve offset.', required: true },
    ],
    defaultPolicy: 'paper-trading',
    defaultProfile: null,
    execution: {
      safeByDefault: true,
      operationExpected: false,
      mutating: false,
      supportsRemote: false,
    },
    tags: ['pari', 'deploy', 'preview', 'dry-run'],
    source: 'first-party',
    approvalStatus: 'approved',
    riskLevel: 'dry-run',
    docs: 'docs/skills/trading-workflows.md',
    benchmark: null,
  }),
  Object.freeze({
    schemaVersion: '1.0.0',
    kind: 'recipe',
    id: 'poly.positions.check',
    version: '1.0.0',
    displayName: 'Polymarket Positions Check',
    description: 'Read Polymarket YES/NO positions, balances, and merge readiness for a wallet.',
    summary: 'Read-only Polymarket inventory check for one wallet.',
    tool: 'polymarket.positions',
    commandTemplate: ['polymarket', 'positions', '--wallet', '{{wallet}}', '--source', 'auto'],
    inputs: [
      { key: 'wallet', type: 'string', description: 'Wallet or proxy address to inspect.', required: true },
    ],
    defaultPolicy: null,
    defaultProfile: null,
    execution: {
      safeByDefault: true,
      operationExpected: false,
      mutating: false,
      supportsRemote: true,
    },
    tags: ['polymarket', 'positions', 'wallet', 'inventory'],
    source: 'first-party',
    approvalStatus: 'approved',
    riskLevel: 'read-only',
    docs: 'docs/skills/mirror-operations.md',
    benchmark: null,
  }),
  Object.freeze({
    schemaVersion: '1.0.0',
    kind: 'recipe',
    id: 'arb.scan.poly',
    version: '1.0.0',
    displayName: 'Arb Scan (Polymarket)',
    description: 'Run one bounded Polymarket arbitrage scan iteration with the MCP-safe JSON contract.',
    summary: 'Bounded read-only arb scan recipe for Pandora versus Polymarket.',
    tool: 'arb.scan',
    commandTemplate: ['arb', 'scan', '--source', 'polymarket', '--output', 'json', '--iterations', '1'],
    inputs: [],
    defaultPolicy: null,
    defaultProfile: null,
    execution: {
      safeByDefault: true,
      operationExpected: false,
      mutating: false,
      supportsRemote: true,
    },
    tags: ['arb', 'scan', 'polymarket', 'scouting'],
    source: 'first-party',
    approvalStatus: 'approved',
    riskLevel: 'read-only',
    docs: 'docs/skills/command-reference.md',
    benchmark: null,
  }),
]);

module.exports = {
  BUILTIN_RECIPES,
};
