const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const pkg = require(path.resolve(__dirname, '..', '..', 'package.json'));

test('package exposes pandora bin entrypoint', () => {
  assert.equal(pkg.name, 'pandora-cli-skills');
  assert.equal(pkg.bin.pandora, 'cli/pandora.cjs');
  assert.ok(pkg.scripts['test:smoke']);
  assert.ok(pkg.scripts['check:docs']);
  assert.equal(pkg.exports['./sdk/typescript'], './sdk/typescript/index.js');
  assert.equal(pkg.exports['./sdk/generated'], './sdk/generated/index.js');
  assert.equal(pkg.exports['./sdk/typescript/generated'], './sdk/typescript/generated/index.js');
  assert.equal(pkg.exports['./sdk/typescript/generated/contract-registry'], './sdk/generated/contract-registry.json');
  assert.ok(pkg.files.includes('cli/pandora.cjs'));
  assert.ok(pkg.files.includes('cli/lib/**'));
  assert.ok(pkg.files.includes('sdk/generated/**'));
  assert.ok(pkg.files.includes('sdk/typescript/index.js'));
  assert.ok(pkg.files.includes('sdk/typescript/generated/index.js'));
  assert.ok(pkg.files.includes('sdk/typescript/generated/manifest.json'));
  assert.ok(pkg.files.includes('sdk/python/pandora_agent/**'));
  assert.ok(pkg.files.includes('!sdk/python/pandora_agent/generated/**'));
  assert.ok(pkg.files.includes('sdk/python/pandora_agent/generated/manifest.json'));
  assert.ok(pkg.files.includes('!sdk/python/pandora_agent/__pycache__/**'));
  assert.ok(pkg.files.includes('!sdk/python/pandora_agent/**/*.pyc'));
  assert.equal(pkg.files.includes('sdk/python/**'), false);
  assert.ok(pkg.files.includes('scripts/create_market_launcher.ts'));
  assert.ok(pkg.files.includes('scripts/create_polymarket_clone_and_bet.ts'));
  assert.ok(pkg.files.includes('docs/skills/**'));
  assert.ok(pkg.files.includes('docs/trust/**'));
  assert.ok(pkg.files.includes('benchmarks/latest/core-report.json'));
  assert.ok(pkg.files.includes('scripts/release/install_release.sh'));
});

test('doc router and scoped skills are present on disk', () => {
  const root = path.resolve(__dirname, '..', '..');
  const readmePath = path.join(root, 'README.md');
  const shareableReadmePath = path.join(root, 'README_FOR_SHARING.md');
  const skillPath = path.join(root, 'SKILL.md');
  const commandReferencePath = path.join(root, 'docs', 'skills', 'command-reference.md');
  const capabilitiesPath = path.join(root, 'docs', 'skills', 'capabilities.md');
  const agentInterfacesPath = path.join(root, 'docs', 'skills', 'agent-interfaces.md');
  const agentQuickstartPath = path.join(root, 'docs', 'skills', 'agent-quickstart.md');
  const tradingWorkflowsPath = path.join(root, 'docs', 'skills', 'trading-workflows.md');
  const portfolioCloseoutPath = path.join(root, 'docs', 'skills', 'portfolio-closeout.md');
  const policyProfilesPath = path.join(root, 'docs', 'skills', 'policy-profiles.md');
  const releaseVerificationPath = path.join(root, 'docs', 'trust', 'release-verification.md');
  const securityModelPath = path.join(root, 'docs', 'trust', 'security-model.md');
  const supportMatrixPath = path.join(root, 'docs', 'trust', 'support-matrix.md');

  assert.equal(fs.existsSync(readmePath), true);
  assert.equal(fs.existsSync(shareableReadmePath), true);
  assert.equal(fs.existsSync(skillPath), true);
  assert.equal(fs.existsSync(commandReferencePath), true);
  assert.equal(fs.existsSync(capabilitiesPath), true);
  assert.equal(fs.existsSync(agentInterfacesPath), true);
  assert.equal(fs.existsSync(agentQuickstartPath), true);
  assert.equal(fs.existsSync(tradingWorkflowsPath), true);
  assert.equal(fs.existsSync(portfolioCloseoutPath), true);
  assert.equal(fs.existsSync(policyProfilesPath), true);
  assert.equal(fs.existsSync(releaseVerificationPath), true);
  assert.equal(fs.existsSync(securityModelPath), true);
  assert.equal(fs.existsSync(supportMatrixPath), true);

  const readmeText = fs.readFileSync(readmePath, 'utf8');
  const shareableReadmeText = fs.readFileSync(shareableReadmePath, 'utf8');
  const skillText = fs.readFileSync(skillPath, 'utf8');
  const commandReferenceText = fs.readFileSync(commandReferencePath, 'utf8');
  const capabilitiesText = fs.readFileSync(capabilitiesPath, 'utf8');
  const agentInterfacesText = fs.readFileSync(agentInterfacesPath, 'utf8');
  const agentQuickstartText = fs.readFileSync(agentQuickstartPath, 'utf8');
  const tradingWorkflowsText = fs.readFileSync(tradingWorkflowsPath, 'utf8');
  const portfolioCloseoutText = fs.readFileSync(portfolioCloseoutPath, 'utf8');
  const policyProfilesText = fs.readFileSync(policyProfilesPath, 'utf8');
  const releaseVerificationText = fs.readFileSync(releaseVerificationPath, 'utf8');
  const securityModelText = fs.readFileSync(securityModelPath, 'utf8');
  const supportMatrixText = fs.readFileSync(supportMatrixPath, 'utf8');
  assert.match(readmeText, /SDK And Contract Export/);
  assert.match(readmeText, /transports\.sdk/);
  assert.match(readmeText, /registryDigest\.descriptorHash/);
  assert.match(shareableReadmeText, /SDK And Contract Export/);
  assert.match(shareableReadmeText, /SDK alpha source\/artifact surfaces/i);
  assert.match(skillText, /pandora --output json capabilities/);
  assert.match(skillText, /SDK alpha source\/artifact surfaces/i);
  assert.match(skillText, /docs\/skills\/command-reference\.md/);
  assert.match(skillText, /docs\/skills\/agent-quickstart\.md/);
  assert.match(skillText, /docs\/skills\/trading-workflows\.md/);
  assert.match(skillText, /docs\/skills\/portfolio-closeout\.md/);
  assert.match(skillText, /docs\/skills\/policy-profiles\.md/);
  assert.match(skillText, /pandora mcp/);
  assert.match(commandReferenceText, /High-value command routing reference/);
  assert.match(commandReferenceText, /pandora --output json schema/);
  assert.match(commandReferenceText, /compact digest, not the full contract surface/i);
  assert.match(commandReferenceText, /pandora mcp/);
  assert.match(commandReferenceText, /sports create run/);
  assert.match(commandReferenceText, /agentPreflight/);
  assert.match(commandReferenceText, /--category/);
  assert.match(commandReferenceText, /--polymarket-rpc-url/);
  assert.match(capabilitiesText, /Small-doc routing/);
  assert.match(capabilitiesText, /Agent-native integration/);
  assert.match(capabilitiesText, /Contract export for SDK generators/);
  assert.match(capabilitiesText, /commandDescriptorVersion/);
  assert.match(capabilitiesText, /capabilities/);
  assert.match(agentInterfacesText, /SDK generation and contract export/);
  assert.match(agentInterfacesText, /npm run generate:sdk-contracts/);
  assert.match(agentInterfacesText, /odds\.record/);
  assert.match(agentInterfacesText, /sports sync run\|start/);
  assert.match(agentQuickstartText, /Preferred bootstrap order/);
  assert.match(agentQuickstartText, /pandora mcp http/);
  assert.match(tradingWorkflowsText, /trade --output json --dry-run/);
  assert.match(tradingWorkflowsText, /sell --output json --dry-run/);
  assert.match(portfolioCloseoutText, /operations list/);
  assert.match(portfolioCloseoutText, /mirror close/);
  assert.match(policyProfilesText, /policy list/);
  assert.match(policyProfilesText, /profile list/);
  assert.match(releaseVerificationText, /gh attestation verify/);
  assert.match(releaseVerificationText, /sbom\.spdx\.json/);
  assert.match(securityModelText, /Remote gateway auth model/);
  assert.match(supportMatrixText, /Trust docs/);
});
